controller:
  sdwan:
    port: 1800
    heartTimeout: 30000
    tenantConfig:
      tenant1:
        vipCidr: 10.5.0.0/24
  relay:
    bindPort: 2478
    heartTimeout: 15000
  stun:
    bindHost: 127.0.0.1
    bindPort: 3478