sdwan:
  sdwanServer:
    enable: true
    port: 1800
    heartTimeout: 30000
    tenantConfig:
      default:
        stunServer: 127.0.0.1:3478
        relayServer: 127.0.0.1:2478
        vipCidr: 10.5.0.0/24
  relayServer:
    enable: true
    bindPort: 2478
    heartTimeout: 15000
  stunServer:
    enable: true
    bindHost: 127.0.0.1
    bindPort: 3478