sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Access-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

server:
  port: 11805

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    dbType: derby
    path: ${user.dir}/derby
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

sdwan:
  httpServer:
    controllerAddress: 127.0.0.1:${sdwan.controllerServer.port}
    storage: ${user.dir}/storage
  controllerServer:
    enable: true
    port: 1800
    heartTimeout: 30000
  stunServer:
    enable: true
    bindHost: 127.0.0.1
    bindPort: 3478
  relayServer:
    enable: true
    bindPort: 2478
    heartTimeout: 15000