### add
POST http://localhost:11805/group/add
Content-Type: application/json
Access-Token: {{token}}

{
  "name": "test",
  "description": "test"
}

### edit
POST http://localhost:11805/group/edit
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 3,
  "name": "test5",
  "description": "test5"
}

### page
GET http://127.0.0.1:11805/group/page
Content-Type: application/json
Access-Token: {{token}}

### del
POST http://127.0.0.1:11805/group/del
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1
}

### updateMemberList
POST http://localhost:11805/group/updateMemberList
Content-Type: application/json
Access-Token: {{token}}

{
  "groupId": 1,
  "memberIdList": [
    6,
    7
  ]
}

### queryMemberList
GET http://localhost:11805/group/memberList/1
Content-Type: application/json
Access-Token: {{token}}