### add
POST http://localhost:11805/node/add
Content-Type: application/json
X-Tenant-Id: 1

{
  "name": "test",
  "description": "test",
  "mac": "test",
  "enable": true
}

### edit
POST http://localhost:11805/node/edit
Content-Type: application/json
X-Tenant-Id: 1

{
  "id": 8,
  "name": "test",
  "description": "test",
  "enable": true,
  "groupIdList": []
}

### page
GET http://127.0.0.1:11805/node/page
Content-Type: application/json
X-Tenant-Id: 1

### detail
GET http://127.0.0.1:11805/node/detail/7
Content-Type: application/json
X-Tenant-Id: 1

### del
POST http://127.0.0.1:11805/node/del
Content-Type: application/json
X-Tenant-Id: 1

{
  "id": 1
}