### add
POST http://localhost:11805/node/add
Content-Type: application/json
Access-Token: {{token}}

{
  "name": "test",
  "description": "test",
  "mac": "test",
  "enable": true
}

### edit
POST http://localhost:11805/node/edit
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 8,
  "name": "test",
  "description": "test",
  "enable": true,
  "groupIdList": []
}

### list
GET http://127.0.0.1:11805/node/list
Content-Type: application/json
Access-Token: {{token}}

### detail
GET http://127.0.0.1:11805/node/detail/7
Content-Type: application/json
Access-Token: {{token}}

### del
POST http://127.0.0.1:11805/node/del
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1
}