### add
POST http://localhost:11805/tenant/add
Content-Type: application/json
Access-Token: {{token}}

{
  "name": "test3",
  "description": "test3",
  "code": "test3",
  "cidr": "10.5.0.0/24",
  "username": "te111st2",
  "password": "te111st",
  "stunServerList": [
    "127.0.0.1:888"
  ],
  "relayServerList": [
    "127.0.0.1:888"
  ],
  "enable": true,
  "nodeGrant": true
}

### edit
POST http://localhost:11805/tenant/edit
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 3,
  "name": "test22",
  "description": "test22",
  "cidr": "10.5.0.0/16",
  "password": "test22",
  "stunServerList": [
    "127.0.0.1"
  ],
  "relayServerList": [
    "127.0.0.1"
  ],
  "enable": true
}

### page
GET http://127.0.0.1:11805/tenant/page
Content-Type: application/json
Access-Token: {{token}}

### del
POST http://127.0.0.1:11805/tenant/del
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1
}