### add
POST http://localhost:11805/api/tenant/add
Content-Type: application/json
Access-Token: {{token}}

{
  "name": "default",
  "description": "default",
  "code": "default",
  "username": "default",
  "password": "12345678",
  "cidr": "15.5.0.0/24",
  "stunServerList": [
    "127.0.0.1:80"
  ],
  "relayServerList": [
    "127.0.0.1:80"
  ],
  "nodeGrant": true,
  "enable": true
}

### edit
POST http://localhost:11805/tenant/edit
Content-Type: application/json
Access-Token: {{token}}

### edit
POST http://localhost:11805/tenant/edit
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 6,
  "name": "ttttttttttt",
  "description": "ttttttttttt",
  "code": "tttttt",
  "cidr": "192.222.0.1/24",
  "username": "ttttttttttt",
  "stunServerList": [
    "192.222.0.1:80"
  ],
  "relayServerList": [
    "192.222.0.1:80"
  ],
  "enable": true,
  "nodeGrant": true,
  "totalNode": 0,
  "onlineNode": 0,
  "password": "ttttttttttt"
}

### page
GET http://127.0.0.1:11805/tenant/page
Content-Type: application/json
Access-Token: {{token}}

### del
POST http://127.0.0.1:11805/tenant/del
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1
}