### add
POST http://localhost:11805/vnat/add
Content-Type: application/json
Access-Token: {{token}}

{
  "name": "test",
  "description": "test",
  "srcCidr": "18.5.1.0/24",
  "dstCidr": "18.5.2.0/24",
  "enable": true
}

### edit
POST http://localhost:11805/vnat/edit
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1,
  "name": "test2",
  "description": "test2",
  "srcCidr": "10.5.1.0/16",
  "dstCidr": "10.5.2.0/16",
  "enable": false
}

### page
GET http://127.0.0.1:11805/vnat/page
Content-Type: application/json
Access-Token: {{token}}

### del
POST http://127.0.0.1:11805/vnat/del
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1
}

### updateConfigList
POST http://127.0.0.1:11805/vnat/updateConfigList
Content-Type: application/json
Access-Token: {{token}}

{
  "id": 1,
  "groupIdList": [
    1
  ]
}

### queryConfigList
GET http://127.0.0.1:11805/vnat/configList/1
Content-Type: application/json
Access-Token: {{token}}