create table biz_account
(
    id    bigint      not null generated by default as identity,
    uname varchar(20) not null,
    pwd   varchar(20) not null,
    role  varchar(64) not null,
    primary key (id)
);

create table biz_app_version
(
    id          bigint                              not null generated by default as identity,
    name        varchar(128)                        not null,
    description varchar(128),
    path        clob                                not null,
    zip_path    clob                                not null,
    zip_md5     varchar(64)                         not null,
    jar_path    clob                                not null,
    jar_md5     varchar(64)                         not null,
    platform    varchar(64)                         not null,
    create_time timestamp default CURRENT_TIMESTAMP not null,
    primary key (id)
);

create table biz_group
(
    id            bigint      not null generated by default as identity,
    name          varchar(64) not null,
    description   varchar(128),
    default_group smallint    not null,
    tenant_id     bigint      not null,
    primary key (id)
);

create table biz_group_member
(
    id        bigint not null generated by default as identity,
    group_id  bigint not null,
    member_id bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

create table biz_group_route
(
    id        bigint not null generated by default as identity,
    group_id  bigint not null,
    route_id  bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

create table biz_group_rule
(
    id        bigint not null generated by default as identity,
    group_id  bigint not null,
    rule_id   bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

create table biz_group_vnat
(
    id        bigint not null generated by default as identity,
    group_id  bigint not null,
    vnat_id   bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

create table biz_node
(
    id          bigint      not null generated by default as identity,
    name        varchar(64),
    description varchar(128),
    mac         varchar(64) not null,
    vip         varchar(16),
    enable      smallint    not null,
    tenant_id   bigint      not null,
    primary key (id)
);

create table biz_route
(
    id          bigint      not null generated by default as identity,
    name        varchar(64) not null,
    description varchar(128),
    destination varchar(128),
    enable      smallint    not null,
    tenant_id   bigint      not null,
    primary key (id)
);

create table biz_route_node_item
(
    id        bigint not null generated by default as identity,
    route_id  bigint not null,
    node_id   bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

create table biz_route_rule
(
    id          bigint      not null generated by default as identity,
    name        varchar(64) not null,
    description varchar(128),
    strategy    varchar(16) not null,
    direction   varchar(16) not null,
    level       int         not null,
    rule_list   clob        not null,
    enable      smallint    not null,
    tenant_id   bigint      not null,
    primary key (id)
);

create table biz_tenant
(
    id          bigint              not null generated by default as identity,
    name        varchar(64)         not null,
    description varchar(128),
    code        varchar(64)         not null,
    cidr        varchar(64)         not null,
    config      clob                not null,
    enable      smallint            not null,
    ip_index    int      default -1 not null,
    account_id  bigint              not null,
    node_grant  smallint default 0  not null,
    primary key (id)
);

create table biz_vip_pool
(
    id        bigint             not null generated by default as identity,
    vip       varchar(16)        not null,
    used      smallint default 0 not null,
    tenant_id bigint             not null,
    primary key (id)
);

create table biz_vnat
(
    id          bigint      not null generated by default as identity,
    name        varchar(64) not null,
    description varchar(128),
    src_cidr    varchar(16) not null,
    dst_cidr    varchar(16) not null,
    enable      smallint    not null,
    tenant_id   bigint      not null,
    primary key (id)
);

create table biz_vnat_node_item
(
    id        bigint not null generated by default as identity,
    vnat_id   bigint not null,
    node_id   bigint not null,
    tenant_id bigint not null,
    primary key (id)
);

INSERT INTO biz_account (uname, pwd, role)
VALUES ('root', 'thunder', 'Root');
