# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # Maven
      - name: Build with Maven
        run: mvn package --file $GITHUB_WORKSPACE/pom.xml -DskipTests
      - name: Copy Controller
        run: cp $GITHUB_WORKSPACE/sdwan-controller/target/sdwan-controller.jar $GITHUB_WORKSPACE/docker/
      - name: Copy Bootstrap
        run: cp $GITHUB_WORKSPACE/sdwan-node-bootstrap/target/sdwan-node-bootstrap.jar $GITHUB_WORKSPACE/docker/
      - name: Checkfile
        run: ls $GITHUB_WORKSPACE/docker/
      # Windows
      - name: Package Windows
        run: |
          mkdir -p $GITHUB_WORKSPACE/distribution
          cd $GITHUB_WORKSPACE/distribution
          wget https://github.com/net-thunder/net-thunder/releases/download/pre/net-thunder-win-base.tar
          tar -xvf net-thunder-win-base.tar
          cp $GITHUB_WORKSPACE/docker/sdwan-node-bootstrap.jar $GITHUB_WORKSPACE/distribution/net-thunder/app/
      - name: Upload Artifact Windows
        uses: actions/upload-artifact@v4
        with:
          name: net-thunder-win
          path: ${{ github.workspace }}/distribution/net-thunder
      # MacOS
      - name: Package MacOS
        run: |
          mkdir -p $GITHUB_WORKSPACE/distribution
          cd $GITHUB_WORKSPACE/distribution
          wget https://github.com/net-thunder/net-thunder/releases/download/pre/net-thunder-mac-base.tar
          tar -xvf net-thunder-mac-base.tar
          cp $GITHUB_WORKSPACE/docker/sdwan-node-bootstrap.jar $GITHUB_WORKSPACE/distribution/net-thunder.app/Contents/app/
      - name: Upload Artifact MacOS
        uses: actions/upload-artifact@v4
        with:
          name: net-thunder-mac
          path: ${{ github.workspace }}/distribution/net-thunder.app
      # Docker
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: docker/
          push: true
          platforms: linux/amd64
          tags: |
            jaspercloud/net-thunder:latest
